# -*- coding: utf-8 -*-
"""flask_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WKi5GWlGc2UQ6MFKma5uOw4HfAEtIycK
"""

from flask import Flask, render_template, send_file
import pandas as pd
import xml.etree.ElementTree as ET
import os

app = Flask(__name__)

# Ruta donde subiste el XML en PythonAnywhere
XML_PATH = '/home/tu_usuario/mysite/DI_export_ecu.xml'

def get_data():
    tree = ET.parse(XML_PATH)
    root = tree.getroot()
    records = []
    for tr in root.findall('.//TR'):
        # Solo extraemos si tiene los campos básicos de desastres
        if tr.find('serial') is not None and tr.find('evento') is not None:
            records.append({child.tag: child.text for child in tr})

    df = pd.DataFrame(records)
    # FILTRADO PREVIO: Solo mostrar Inundaciones
    df_filtrado = df[df['evento'] == 'Inundación']
    return df_filtrado

@app.route('/')
def index():
    df = get_data()
    # Convertimos a HTML (sin índice y con clases de diseño)
    tabla_html = df.to_html(classes='table table-striped table-hover', index=False)
    return render_template('index.html', tabla=tabla_html)

@app.route('/descargar_xml')
def descargar():
    # Descarga directa desde tu servidor PythonAnywhere
    return send_file(XML_PATH, as_attachment=True)
